/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /Users/bendyer/Projects/ARM/workspace/vectorcontrol/dsdl/thiemar/equipment/esc/11031.ThrustPowerCommand.uavcan
 */

#ifndef THIEMAR_EQUIPMENT_ESC_THRUSTPOWERCOMMAND_HPP_INCLUDED
#define THIEMAR_EQUIPMENT_ESC_THRUSTPOWERCOMMAND_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Simple thrust power setpoint.
# Negative values indicate reverse rotation.
#

float16[<=20] thrust_power    # Watt
******************************************************************************/

/********************* DSDL signature source definition ***********************
thiemar.equipment.esc.ThrustPowerCommand
saturated float16[<=20] thrust_power
******************************************************************************/

#undef thrust_power

namespace thiemar
{
namespace equipment
{
namespace esc
{

template <int _tmpl>
struct UAVCAN_EXPORT ThrustPowerCommand_
{
    typedef const ThrustPowerCommand_<_tmpl>& ParameterType;
    typedef ThrustPowerCommand_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Array< ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeDynamic, 20 > thrust_power;
    };

    enum
    {
        MinBitLen
            = FieldTypes::thrust_power::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::thrust_power::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::thrust_power >::Type thrust_power;

    ThrustPowerCommand_()
        : thrust_power()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<325 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 11031 };

    static const char* getDataTypeFullName()
    {
        return "thiemar.equipment.esc.ThrustPowerCommand";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool ThrustPowerCommand_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        thrust_power == rhs.thrust_power;
}

template <int _tmpl>
bool ThrustPowerCommand_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(thrust_power, rhs.thrust_power);
}

template <int _tmpl>
int ThrustPowerCommand_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::thrust_power::encode(self.thrust_power, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int ThrustPowerCommand_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::thrust_power::decode(self.thrust_power, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature ThrustPowerCommand_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x5734B726BF82CFEAULL);

    FieldTypes::thrust_power::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef ThrustPowerCommand_<0> ThrustPowerCommand;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::thiemar::equipment::esc::ThrustPowerCommand > _uavcan_gdtr_registrator_ThrustPowerCommand;

}

} // Namespace esc
} // Namespace equipment
} // Namespace thiemar

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::thiemar::equipment::esc::ThrustPowerCommand >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::thiemar::equipment::esc::ThrustPowerCommand::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::thiemar::equipment::esc::ThrustPowerCommand >::stream(Stream& s, ::thiemar::equipment::esc::ThrustPowerCommand::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "thrust_power: ";
    YamlStreamer< ::thiemar::equipment::esc::ThrustPowerCommand::FieldTypes::thrust_power >::stream(s, obj.thrust_power, level + 1);
}

}

namespace thiemar
{
namespace equipment
{
namespace esc
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::thiemar::equipment::esc::ThrustPowerCommand::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::thiemar::equipment::esc::ThrustPowerCommand >::stream(s, obj, 0);
    return s;
}

} // Namespace esc
} // Namespace equipment
} // Namespace thiemar

#endif // THIEMAR_EQUIPMENT_ESC_THRUSTPOWERCOMMAND_HPP_INCLUDED