/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /mnt/hgfs/workspace/uavcan/dsdl/uavcan/protocol/file/580.GetInfo.uavcan
 */

#ifndef UAVCAN_PROTOCOL_FILE_GETINFO_HPP_INCLUDED
#define UAVCAN_PROTOCOL_FILE_GETINFO_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

#include <uavcan/protocol/file/EntryType.hpp>
#include <uavcan/protocol/file/Error.hpp>
#include <uavcan/protocol/file/Path.hpp>

/******************************* Source text **********************************
#
# Request info about a remote file system entry (file, directory, etc).
#
# CRC computation algorithm is the same as for DSDL signature (refer to the protocol specification). The CRC field
# should be set to zero for directories.
#
# Size is the file size in bytes. It should be set to zero for directories.
#

Path path

---

uint64 crc64     # Undefined for directories
uint32 size      # Undefined for directories
Error error
EntryType entry_type
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.protocol.file.GetInfo
uavcan.protocol.file.Path path
---
saturated uint64 crc64
saturated uint32 size
uavcan.protocol.file.Error error
uavcan.protocol.file.EntryType entry_type
******************************************************************************/

#undef path
#undef crc64
#undef size
#undef error
#undef entry_type

#ifndef UAVCAN_PACK_STRUCTS
# error UAVCAN_PACK_STRUCTS
#endif

namespace uavcan
{
namespace protocol
{
namespace file
{

#if UAVCAN_PACK_STRUCTS
UAVCAN_PACKED_BEGIN
#endif

struct UAVCAN_EXPORT GetInfo_
{
    template <int _tmpl>
    struct Request_
    {
        typedef const Request_<_tmpl>& ParameterType;
        typedef Request_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
        };

        struct FieldTypes
        {
            typedef ::uavcan::protocol::file::Path path;
        };

        enum
        {
            MinBitLen
                = FieldTypes::path::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::path::MaxBitLen
        };

        // Constants

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::path >::Type path;

        Request_()
            : path()
        {
            enum { MaxByteLen = ::uavcan::BitLenToByteLen<MaxBitLen>::Result };
            ::uavcan::StaticAssert<int(MaxByteLen) <= int(::uavcan::MaxTransferPayloadLen)>::check();

            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<1608 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);
    };

    template <int _tmpl>
    struct Response_
    {
        typedef const Response_<_tmpl>& ParameterType;
        typedef Response_<_tmpl>& ReferenceType;

        struct ConstantTypes
        {
        };

        struct FieldTypes
        {
            typedef ::uavcan::IntegerSpec< 64, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > crc64;
            typedef ::uavcan::IntegerSpec< 32, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > size;
            typedef ::uavcan::protocol::file::Error error;
            typedef ::uavcan::protocol::file::EntryType entry_type;
        };

        enum
        {
            MinBitLen
                = FieldTypes::crc64::MinBitLen
                + FieldTypes::size::MinBitLen
                + FieldTypes::error::MinBitLen
                + FieldTypes::entry_type::MinBitLen
        };

        enum
        {
            MaxBitLen
                = FieldTypes::crc64::MaxBitLen
                + FieldTypes::size::MaxBitLen
                + FieldTypes::error::MaxBitLen
                + FieldTypes::entry_type::MaxBitLen
        };

        // Constants

        // Fields
        typename ::uavcan::StorageType< typename FieldTypes::crc64 >::Type crc64;
        typename ::uavcan::StorageType< typename FieldTypes::size >::Type size;
        typename ::uavcan::StorageType< typename FieldTypes::error >::Type error;
        typename ::uavcan::StorageType< typename FieldTypes::entry_type >::Type entry_type;

        Response_()
            : crc64()
            , size()
            , error()
            , entry_type()
        {
            enum { MaxByteLen = ::uavcan::BitLenToByteLen<MaxBitLen>::Result };
            ::uavcan::StaticAssert<int(MaxByteLen) <= int(::uavcan::MaxTransferPayloadLen)>::check();

            ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

    #if UAVCAN_DEBUG
            /*
             * Cross-checking MaxBitLen provided by the DSDL compiler.
             * This check shall never be performed in user code because MaxBitLen value
             * actually depends on the nested types, thus it is not invariant.
             */
            ::uavcan::StaticAssert<120 == MaxBitLen>::check();
    #endif
        }

        bool operator==(ParameterType rhs) const;
        bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

        /**
         * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
         * floating point fields at any depth.
         */
        bool isClose(ParameterType rhs) const;

        static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

        static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                          ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);
    };

    typedef Request_<0> Request;
    typedef Response_<0> Response;

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindService };
    enum { DefaultDataTypeID = 580 };

    static const char* getDataTypeFullName()
    {
        return "uavcan.protocol.file.GetInfo";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

private:
    GetInfo_(); // Don't create objects of this type. Use Request/Response instead.
};

#if UAVCAN_PACK_STRUCTS
UAVCAN_PACKED_END
#endif

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool GetInfo_::Request_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        path == rhs.path;
}

template <int _tmpl>
bool GetInfo_::Request_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(path, rhs.path);
}

template <int _tmpl>
int GetInfo_::Request_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::path::encode(self.path, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int GetInfo_::Request_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::path::decode(self.path, codec,  tao_mode);
    return res;
}

template <int _tmpl>
bool GetInfo_::Response_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        crc64 == rhs.crc64 &&
        size == rhs.size &&
        error == rhs.error &&
        entry_type == rhs.entry_type;
}

template <int _tmpl>
bool GetInfo_::Response_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(crc64, rhs.crc64) &&
        ::uavcan::areClose(size, rhs.size) &&
        ::uavcan::areClose(error, rhs.error) &&
        ::uavcan::areClose(entry_type, rhs.entry_type);
}

template <int _tmpl>
int GetInfo_::Response_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::crc64::encode(self.crc64, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::size::encode(self.size, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::error::encode(self.error, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::entry_type::encode(self.entry_type, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int GetInfo_::Response_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::crc64::decode(self.crc64, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::size::decode(self.size, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::error::decode(self.error, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::entry_type::decode(self.entry_type, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
inline ::uavcan::DataTypeSignature GetInfo_::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x22431DB8493110E1ULL);

    Request::FieldTypes::path::extendDataTypeSignature(signature);

    Response::FieldTypes::crc64::extendDataTypeSignature(signature);
    Response::FieldTypes::size::extendDataTypeSignature(signature);
    Response::FieldTypes::error::extendDataTypeSignature(signature);
    Response::FieldTypes::entry_type::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef GetInfo_ GetInfo;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::uavcan::protocol::file::GetInfo > _uavcan_gdtr_registrator_GetInfo;

}

} // Namespace uavcan
} // Namespace protocol
} // Namespace file

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::uavcan::protocol::file::GetInfo::Request >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::uavcan::protocol::file::GetInfo::Request::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::uavcan::protocol::file::GetInfo::Request >::stream(Stream& s, ::uavcan::protocol::file::GetInfo::Request::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "path: ";
    YamlStreamer< ::uavcan::protocol::file::GetInfo::Request::FieldTypes::path >::stream(s, obj.path, level + 1);
}

template <>
class UAVCAN_EXPORT YamlStreamer< ::uavcan::protocol::file::GetInfo::Response >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::uavcan::protocol::file::GetInfo::Response::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::uavcan::protocol::file::GetInfo::Response >::stream(Stream& s, ::uavcan::protocol::file::GetInfo::Response::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "crc64: ";
    YamlStreamer< ::uavcan::protocol::file::GetInfo::Response::FieldTypes::crc64 >::stream(s, obj.crc64, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "size: ";
    YamlStreamer< ::uavcan::protocol::file::GetInfo::Response::FieldTypes::size >::stream(s, obj.size, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "error: ";
    YamlStreamer< ::uavcan::protocol::file::GetInfo::Response::FieldTypes::error >::stream(s, obj.error, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "entry_type: ";
    YamlStreamer< ::uavcan::protocol::file::GetInfo::Response::FieldTypes::entry_type >::stream(s, obj.entry_type, level + 1);
}

}

namespace uavcan
{
namespace protocol
{
namespace file
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::uavcan::protocol::file::GetInfo::Request::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::uavcan::protocol::file::GetInfo::Request >::stream(s, obj, 0);
    return s;
}

template <typename Stream>
inline Stream& operator<<(Stream& s, ::uavcan::protocol::file::GetInfo::Response::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::uavcan::protocol::file::GetInfo::Response >::stream(s, obj, 0);
    return s;
}

}
}
}

#endif // UAVCAN_PROTOCOL_FILE_GETINFO_HPP_INCLUDED